### ISSUE TITLE
Визуальный редактор Editorjs

### ISSUE THREAD

**Issue by mikhnyuk** [ADamCarraway/journalphp#1]
Если будет добавлен визуальный редактор как в tj, dtf, vc - было бы круто. Понравился клон dtf (хоть и не работали некоторые функции удалить коммент, в добавлении статьи не добавлялись ссылки), надеюсь journalphp будет в похожем стиле 👍

**Comment by ADamCarraway** [comment]
> Если будет добавлен визуальный редактор как в tj, dtf, vc - было бы круто. Понравился клон dtf (хоть и не работали некоторые функции удалить коммент, в добавлении статьи не добавлялись ссылки), надеюсь journalphp будет в похожем стиле 👍

Спасибо за фитбек! В скором времени будет готовый прототип (не доходят руки доделать админку минимальную). Затем залью в репо и сделаю demo чтобы можно было протестировать и пофиксить баги.
